"""fix charity project model

Revision ID: 0b82a88e4fdb
Revises: b025f5863474
Create Date: 2023-10-19 00:13:17.108505

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '0b82a88e4fdb'
down_revision = 'b025f5863474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charityproject', 'full_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charityproject', 'full_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
